#define OMEN_ROUNDSTART "roundstart"
#define OMEN_NOLORD "nolord"
#define OMEN_NOPRIEST "nopriest"
#define OMEN_NOBLEDEATH "nobledeath"
#define OMEN_SUNSTEAL "sunsteal"
#define OMEN_SKELETONSIEGE "skeletonsiege"
